[package]
name = "agent-viewer-tui"
version = "0.1.0"
edition = "2024"

[lib]
name = "agent_viewer_tui"
path = "src/lib.rs"

[[bin]]
name = "agent-viewer"
path = "src/main.rs"

[dependencies]
agent-viewer-core = { version = "0.1.0", path = "../agent-viewer-core" }
crossterm = "0.29.0"
ratatui = "0.30.2"
tui-term = "0.3.4"

[dev-dependencies]
tempfile = "3.27.0"
